language: cpp

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
  - windows

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
    else
      sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
      sudo apt-get update -qq ;
    fi

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install qt5;
    else
      sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qt5-default ;
      sudo apt-get install -qq libudev-dev ;
      sudo apt-get install -qq xorg-dev ;
      sudo apt-get install -qq freeglut3-dev ;
      sudo pip install requests ;
    fi

script:
 - qmake -project
 - qmake Library.pro
 - make
