language: cpp

sudo: required

dist: trusty

compiler:
  - clang

os:
  - linux
  - osx
  - windows

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
    else
      sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
      sudo apt-get update -qq ;
    fi

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install qt;
    else
      sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qt5-default libudev-dev;
    fi

script:
 - qmake -project
 - qmake "QT += core gui sql widgets" Library.pro
 - make
