language: cpp

sudo: required

dist: trusty

compiler:
  - clang

os:
  - linux
  - osx
  - windows

before_install:
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update > /dev/null
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
   else
      sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
      && sudo apt-get update -qq
      && sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev -y
      && sudo apt-get install qt5-default qttools5-dev-tools -y
      ;
   fi

script:
 - qmake -project
 - qmake *.pro
 - make
